"""create phase one schema

Revision ID: fff93032eb16
Revises:
Create Date: 2026-08-15 02:34:22.252624
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "fff93032eb16"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "analysis_jobs",
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column("current_stage", sa.String(length=64), nullable=True),
        sa.Column("checkpoint_cursor", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_by", sa.String(length=255), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_jobs")),
        sa.UniqueConstraint(
            "idempotency_key", "pipeline_version", name=op.f("uq_analysis_jobs_idempotency_key")
        ),
    )
    op.create_index(op.f("ix_analysis_jobs_status"), "analysis_jobs", ["status"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("before_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_correlation_id"), "audit_logs", ["correlation_id"], unique=False
    )
    op.create_table(
        "canonical_entities",
        sa.Column("source_namespace", sa.String(length=128), nullable=False),
        sa.Column("source_entity_key", sa.String(length=255), nullable=False),
        sa.Column("standard_name", sa.String(length=512), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("administrative_code", sa.String(length=32), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_entities")),
        sa.UniqueConstraint(
            "source_namespace",
            "source_entity_key",
            name=op.f("uq_canonical_entities_source_namespace"),
        ),
    )
    op.create_index(
        op.f("ix_canonical_entities_administrative_code"),
        "canonical_entities",
        ["administrative_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_entities_standard_name"),
        "canonical_entities",
        ["standard_name"],
        unique=False,
    )
    op.create_table(
        "import_batches",
        sa.Column("source_filename", sa.String(length=512), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sheet_name", sa.String(length=255), nullable=True),
        sa.Column("field_mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("successful_rows", sa.Integer(), nullable=False),
        sa.Column("failed_rows", sa.Integer(), nullable=False),
        sa.Column("duplicate_rows", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
        sa.UniqueConstraint("source_sha256", name=op.f("uq_import_batches_source_sha256")),
    )
    op.create_table(
        "knowledge_snapshots",
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.String(length=128), nullable=True),
        sa.Column("built_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entity_count", sa.Integer(), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_snapshots")),
        sa.UniqueConstraint("snapshot_hash", name=op.f("uq_knowledge_snapshots_snapshot_hash")),
        sa.UniqueConstraint("version", name=op.f("uq_knowledge_snapshots_version")),
    )
    op.create_table(
        "analysis_runs",
        sa.Column("analysis_job_id", sa.Uuid(), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=True),
        sa.Column("model_config_hash", sa.String(length=64), nullable=True),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("knowledge_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_analysis_runs_analysis_job_id_analysis_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_snapshot_id"],
            ["knowledge_snapshots.id"],
            name=op.f("fk_analysis_runs_knowledge_snapshot_id_knowledge_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_runs")),
    )
    op.create_index(
        op.f("ix_analysis_runs_analysis_job_id"), "analysis_runs", ["analysis_job_id"], unique=False
    )
    op.create_table(
        "entity_aliases_runtime",
        sa.Column("knowledge_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_entity_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=512), nullable=False),
        sa.Column("alias_type", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_entity_id"],
            ["canonical_entities.id"],
            name=op.f("fk_entity_aliases_runtime_canonical_entity_id_canonical_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_snapshot_id"],
            ["knowledge_snapshots.id"],
            name=op.f("fk_entity_aliases_runtime_knowledge_snapshot_id_knowledge_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_aliases_runtime")),
        sa.UniqueConstraint(
            "knowledge_snapshot_id",
            "alias",
            "canonical_entity_id",
            name=op.f("uq_entity_aliases_runtime_knowledge_snapshot_id"),
        ),
    )
    op.create_index(
        op.f("ix_entity_aliases_runtime_alias"), "entity_aliases_runtime", ["alias"], unique=False
    )
    op.create_index(
        op.f("ix_entity_aliases_runtime_canonical_entity_id"),
        "entity_aliases_runtime",
        ["canonical_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_aliases_runtime_knowledge_snapshot_id"),
        "entity_aliases_runtime",
        ["knowledge_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "event_clusters",
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("handling_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=True),
        sa.Column("model_config_hash", sa.String(length=64), nullable=True),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("knowledge_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_snapshot_id"],
            ["knowledge_snapshots.id"],
            name=op.f("fk_event_clusters_knowledge_snapshot_id_knowledge_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_clusters")),
    )
    op.create_table(
        "work_orders",
        sa.Column("import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=False),
        sa.Column("external_work_order_number", sa.String(length=255), nullable=True),
        sa.Column("raw_title", sa.Text(), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=False),
        sa.Column("raw_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_work_orders_import_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_orders")),
        sa.UniqueConstraint(
            "import_batch_id", "source_row_number", name=op.f("uq_work_orders_import_batch_id")
        ),
    )
    op.create_index(
        op.f("ix_work_orders_external_work_order_number"),
        "work_orders",
        ["external_work_order_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_orders_import_batch_id"), "work_orders", ["import_batch_id"], unique=False
    )
    op.create_table(
        "complaint_segments",
        sa.Column("work_order_id", sa.Uuid(), nullable=False),
        sa.Column("segment_type", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_complaint_segments_work_order_id_work_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_segments")),
    )
    op.create_index(
        op.f("ix_complaint_segments_work_order_id"),
        "complaint_segments",
        ["work_order_id"],
        unique=False,
    )
    op.create_table(
        "event_handling_records",
        sa.Column("event_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("previous_status", sa.String(length=32), nullable=True),
        sa.Column("new_status", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("attachment_references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_cluster_id"],
            ["event_clusters.id"],
            name=op.f("fk_event_handling_records_event_cluster_id_event_clusters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_handling_records")),
    )
    op.create_index(
        op.f("ix_event_handling_records_event_cluster_id"),
        "event_handling_records",
        ["event_cluster_id"],
        unique=False,
    )
    op.create_table(
        "event_instances",
        sa.Column("work_order_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=True),
        sa.Column("behavior", sa.Text(), nullable=True),
        sa.Column("normalized_summary", sa.Text(), nullable=False),
        sa.Column("entity_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("location_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("time_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=True),
        sa.Column("model_config_hash", sa.String(length=64), nullable=True),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("knowledge_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_snapshot_id"],
            ["knowledge_snapshots.id"],
            name=op.f("fk_event_instances_knowledge_snapshot_id_knowledge_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_event_instances_work_order_id_work_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_instances")),
    )
    op.create_index(
        op.f("ix_event_instances_event_type"), "event_instances", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_event_instances_work_order_id"), "event_instances", ["work_order_id"], unique=False
    )
    op.create_table(
        "human_corrections",
        sa.Column("correction_type", sa.String(length=64), nullable=False),
        sa.Column("work_order_id", sa.Uuid(), nullable=True),
        sa.Column("event_cluster_id", sa.Uuid(), nullable=True),
        sa.Column("supersedes_correction_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_cluster_id"],
            ["event_clusters.id"],
            name=op.f("fk_human_corrections_event_cluster_id_event_clusters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_correction_id"],
            ["human_corrections.id"],
            name=op.f("fk_human_corrections_supersedes_correction_id_human_corrections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_human_corrections_work_order_id_work_orders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_corrections")),
    )
    op.create_index(
        op.f("ix_human_corrections_event_cluster_id"),
        "human_corrections",
        ["event_cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_human_corrections_work_order_id"),
        "human_corrections",
        ["work_order_id"],
        unique=False,
    )
    op.create_table(
        "entity_mentions",
        sa.Column("work_order_id", sa.Uuid(), nullable=False),
        sa.Column("complaint_segment_id", sa.Uuid(), nullable=True),
        sa.Column("mention_text", sa.Text(), nullable=False),
        sa.Column("mention_type", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("canonical_entity_id", sa.Uuid(), nullable=True),
        sa.Column("resolution_state", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=True),
        sa.Column("model_config_hash", sa.String(length=64), nullable=True),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("knowledge_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_entity_id"],
            ["canonical_entities.id"],
            name=op.f("fk_entity_mentions_canonical_entity_id_canonical_entities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["complaint_segment_id"],
            ["complaint_segments.id"],
            name=op.f("fk_entity_mentions_complaint_segment_id_complaint_segments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_snapshot_id"],
            ["knowledge_snapshots.id"],
            name=op.f("fk_entity_mentions_knowledge_snapshot_id_knowledge_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_entity_mentions_work_order_id_work_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_mentions")),
    )
    op.create_index(
        op.f("ix_entity_mentions_canonical_entity_id"),
        "entity_mentions",
        ["canonical_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_mentions_complaint_segment_id"),
        "entity_mentions",
        ["complaint_segment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_mentions_work_order_id"), "entity_mentions", ["work_order_id"], unique=False
    )
    op.create_table(
        "event_candidates",
        sa.Column("query_event_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_event_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("retrieval_rank", sa.Integer(), nullable=False),
        sa.Column("retrieval_score", sa.Float(), nullable=False),
        sa.Column("rerank_score", sa.Float(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=True),
        sa.Column("model_config_hash", sa.String(length=64), nullable=True),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("knowledge_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_event_candidates_analysis_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_event_id"],
            ["event_instances.id"],
            name=op.f("fk_event_candidates_candidate_event_id_event_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_snapshot_id"],
            ["knowledge_snapshots.id"],
            name=op.f("fk_event_candidates_knowledge_snapshot_id_knowledge_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["query_event_id"],
            ["event_instances.id"],
            name=op.f("fk_event_candidates_query_event_id_event_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_candidates")),
        sa.UniqueConstraint(
            "query_event_id",
            "candidate_event_id",
            "analysis_run_id",
            name=op.f("uq_event_candidates_query_event_id"),
        ),
    )
    op.create_index(
        op.f("ix_event_candidates_analysis_run_id"),
        "event_candidates",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_candidates_candidate_event_id"),
        "event_candidates",
        ["candidate_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_candidates_query_event_id"),
        "event_candidates",
        ["query_event_id"],
        unique=False,
    )
    op.create_table(
        "event_cluster_members",
        sa.Column("event_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("event_instance_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("membership_confidence", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_event_cluster_members_analysis_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_cluster_id"],
            ["event_clusters.id"],
            name=op.f("fk_event_cluster_members_event_cluster_id_event_clusters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_instance_id"],
            ["event_instances.id"],
            name=op.f("fk_event_cluster_members_event_instance_id_event_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_cluster_members")),
        sa.UniqueConstraint(
            "event_cluster_id",
            "event_instance_id",
            name=op.f("uq_event_cluster_members_event_cluster_id"),
        ),
    )
    op.create_index(
        op.f("ix_event_cluster_members_analysis_run_id"),
        "event_cluster_members",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_cluster_members_event_cluster_id"),
        "event_cluster_members",
        ["event_cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_cluster_members_event_instance_id"),
        "event_cluster_members",
        ["event_instance_id"],
        unique=False,
    )
    op.create_table(
        "event_match_edges",
        sa.Column("left_event_id", sa.Uuid(), nullable=False),
        sa.Column("right_event_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_run_id", sa.Uuid(), nullable=False),
        sa.Column("same_event", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=True),
        sa.Column("model_config_hash", sa.String(length=64), nullable=True),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("knowledge_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_event_match_edges_analysis_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_snapshot_id"],
            ["knowledge_snapshots.id"],
            name=op.f("fk_event_match_edges_knowledge_snapshot_id_knowledge_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["left_event_id"],
            ["event_instances.id"],
            name=op.f("fk_event_match_edges_left_event_id_event_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["right_event_id"],
            ["event_instances.id"],
            name=op.f("fk_event_match_edges_right_event_id_event_instances"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_match_edges")),
        sa.UniqueConstraint(
            "left_event_id",
            "right_event_id",
            "analysis_run_id",
            name=op.f("uq_event_match_edges_left_event_id"),
        ),
    )
    op.create_index(
        op.f("ix_event_match_edges_analysis_run_id"),
        "event_match_edges",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_match_edges_left_event_id"),
        "event_match_edges",
        ["left_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_match_edges_right_event_id"),
        "event_match_edges",
        ["right_event_id"],
        unique=False,
    )
    op.create_table(
        "work_order_embeddings",
        sa.Column("work_order_id", sa.Uuid(), nullable=False),
        sa.Column("event_instance_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=True),
        sa.Column("model_config_hash", sa.String(length=64), nullable=True),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("knowledge_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_instance_id"],
            ["event_instances.id"],
            name=op.f("fk_work_order_embeddings_event_instance_id_event_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_snapshot_id"],
            ["knowledge_snapshots.id"],
            name=op.f("fk_work_order_embeddings_knowledge_snapshot_id_knowledge_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_work_order_embeddings_work_order_id_work_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_order_embeddings")),
        sa.UniqueConstraint(
            "work_order_id",
            "content_hash",
            "model_id",
            name=op.f("uq_work_order_embeddings_work_order_id"),
        ),
    )
    op.create_index(
        op.f("ix_work_order_embeddings_event_instance_id"),
        "work_order_embeddings",
        ["event_instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_order_embeddings_work_order_id"),
        "work_order_embeddings",
        ["work_order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_work_order_embeddings_work_order_id"), table_name="work_order_embeddings"
    )
    op.drop_index(
        op.f("ix_work_order_embeddings_event_instance_id"), table_name="work_order_embeddings"
    )
    op.drop_table("work_order_embeddings")
    op.drop_index(op.f("ix_event_match_edges_right_event_id"), table_name="event_match_edges")
    op.drop_index(op.f("ix_event_match_edges_left_event_id"), table_name="event_match_edges")
    op.drop_index(op.f("ix_event_match_edges_analysis_run_id"), table_name="event_match_edges")
    op.drop_table("event_match_edges")
    op.drop_index(
        op.f("ix_event_cluster_members_event_instance_id"), table_name="event_cluster_members"
    )
    op.drop_index(
        op.f("ix_event_cluster_members_event_cluster_id"), table_name="event_cluster_members"
    )
    op.drop_index(
        op.f("ix_event_cluster_members_analysis_run_id"), table_name="event_cluster_members"
    )
    op.drop_table("event_cluster_members")
    op.drop_index(op.f("ix_event_candidates_query_event_id"), table_name="event_candidates")
    op.drop_index(op.f("ix_event_candidates_candidate_event_id"), table_name="event_candidates")
    op.drop_index(op.f("ix_event_candidates_analysis_run_id"), table_name="event_candidates")
    op.drop_table("event_candidates")
    op.drop_index(op.f("ix_entity_mentions_work_order_id"), table_name="entity_mentions")
    op.drop_index(op.f("ix_entity_mentions_complaint_segment_id"), table_name="entity_mentions")
    op.drop_index(op.f("ix_entity_mentions_canonical_entity_id"), table_name="entity_mentions")
    op.drop_table("entity_mentions")
    op.drop_index(op.f("ix_human_corrections_work_order_id"), table_name="human_corrections")
    op.drop_index(op.f("ix_human_corrections_event_cluster_id"), table_name="human_corrections")
    op.drop_table("human_corrections")
    op.drop_index(op.f("ix_event_instances_work_order_id"), table_name="event_instances")
    op.drop_index(op.f("ix_event_instances_event_type"), table_name="event_instances")
    op.drop_table("event_instances")
    op.drop_index(
        op.f("ix_event_handling_records_event_cluster_id"), table_name="event_handling_records"
    )
    op.drop_table("event_handling_records")
    op.drop_index(op.f("ix_complaint_segments_work_order_id"), table_name="complaint_segments")
    op.drop_table("complaint_segments")
    op.drop_index(op.f("ix_work_orders_import_batch_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_external_work_order_number"), table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_table("event_clusters")
    op.drop_index(
        op.f("ix_entity_aliases_runtime_knowledge_snapshot_id"), table_name="entity_aliases_runtime"
    )
    op.drop_index(
        op.f("ix_entity_aliases_runtime_canonical_entity_id"), table_name="entity_aliases_runtime"
    )
    op.drop_index(op.f("ix_entity_aliases_runtime_alias"), table_name="entity_aliases_runtime")
    op.drop_table("entity_aliases_runtime")
    op.drop_index(op.f("ix_analysis_runs_analysis_job_id"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.drop_table("knowledge_snapshots")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_canonical_entities_standard_name"), table_name="canonical_entities")
    op.drop_index(
        op.f("ix_canonical_entities_administrative_code"), table_name="canonical_entities"
    )
    op.drop_table("canonical_entities")
    op.drop_index(op.f("ix_audit_logs_correlation_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_analysis_jobs_status"), table_name="analysis_jobs")
    op.drop_table("analysis_jobs")
    # ### end Alembic commands ###
